/**
 * Generated by `npm run gen:api` from the backend's OpenAPI schema.
 * Do not edit by hand -- CI regenerates this and fails on any difference.
 */

export interface paths {
  '/api/admin/rebuild-caches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Rebuild Caches
     * @description Recompute every leg's replay cache from its darts.
     *
     *     The caches are disposable -- they exist only to resume an interrupted leg --
     *     so this can never lose history, and on a database that is already correct it
     *     changes nothing and reports `legs_changed: 0`.
     */
    post: operations['rebuild_caches_api_admin_rebuild_caches_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/snapshot': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Take Snapshot
     * @description Republish `darts-latest.db` and `snapshot.json` in the snapshot directory.
     *
     *     Safe mid-game: the copy is a point-in-time image taken inside a read
     *     transaction, and it is renamed into place, so a reader on the share either
     *     keeps the file it already opened or gets the new one whole.
     */
    post: operations['take_snapshot_api_admin_snapshot_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/export/darts.csv': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Every recorded dart as one CSV row
     * @description One line per recorded dart, under the header documented in docs/data-model.md.
     */
    get: operations['darts_csv_api_export_darts_csv_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/export/db': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download a fresh point-in-time copy of the database
     * @description A fresh copy, taken now, with its WAL collapsed into it.
     *
     *     The copy is taken here rather than inside the generator so that a failure to
     *     produce it is an error response, not a truncated download.
     */
    get: operations['export_db_api_export_db_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/export/matches.csv': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Every match as one CSV row
     * @description One line per match, with its teams and players flattened into two cells.
     */
    get: operations['matches_csv_api_export_matches_csv_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/export/stats.json': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stats Json
     * @description Every player's report and the leaderboard, read as one consistent whole.
     *
     *     One object per player rather than one per dart, so this is small enough to
     *     build in memory and is an ordinary JSON response rather than a stream.
     */
    get: operations['stats_json_api_export_stats_json_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Database and build health
     * @description 200 while the database is serving, 503 otherwise.
     *
     *     The 503 goes out in the standard error envelope like every other `/api`
     *     failure, with the whole report under `detail` so the reason survives.
     */
    get: operations['healthz_api_healthz_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/legs/{leg_id}/checkout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Checkout
     * @description The same hints `/state` embeds, on their own, for testing and debugging.
     *
     *     Nothing in the app needs this -- the fat read already carries it -- but a
     *     hint that can only be seen inside a hundred-line payload is a hint that is
     *     hard to be sure about.
     */
    get: operations['get_checkout_api_legs__leg_id__checkout_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/legs/{leg_id}/darts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Record Dart
     * @description Record one dart and return the whole new state.
     *
     *     200 rather than 201: the response is the state of the match, not the dart
     *     row, and a retry of a dart already recorded has created nothing. Answering
     *     201 to a request that inserted no row would be a lie the client cannot
     *     check, and #18 asks for the retry to be a plain 200.
     *
     *     Idempotent on `client_dart_id`: a key already recorded inserts nothing and
     *     returns the state *as it stands now*. An immediate retry therefore returns
     *     exactly what the first call did. A retry sent after other darts have landed
     *     returns the newer state, which is the honest answer -- the service does not
     *     store responses and will not replay history. The same key describing a
     *     different dart, or aimed at a different leg, is a 409 rather than somebody
     *     else's throw.
     */
    post: operations['record_dart_api_legs__leg_id__darts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/legs/{leg_id}/undo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Undo Dart
     * @description Delete the leg's last dart and return the state that leaves.
     *
     *     409 for a leg with nothing to undo, for a later leg already played into,
     *     and for an abandoned match.
     */
    post: operations['undo_dart_api_legs__leg_id__undo_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/matches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Matches */
    get: operations['list_matches_api_matches_get']
    put?: never
    /** Create Match */
    post: operations['create_match_api_matches_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/matches/{match_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Match */
    get: operations['get_match_api_matches__match_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/matches/{match_id}/abandon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Abandon Match */
    post: operations['abandon_match_api_matches__match_id__abandon_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/matches/{match_id}/darts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Match Darts
     * @description Every dart of a match, by leg and visit, for #26's dart-by-dart breakdown.
     *
     *     The one thing `/state` structurally cannot answer. It carries two visits of
     *     the current leg, and both move on as the leg does; a finished leg's visits
     *     are not on any later response. Deriving them from a sequence of reads would
     *     mean a client recording state it was never promised, so this is a read of
     *     the rows instead.
     *
     *     404 for a match that does not exist. An abandoned or in-progress match
     *     answers normally -- a part-played leg is simply shorter -- because reading
     *     darts is not acting on them, and #17's refusals are about the latter.
     *
     *     Read-only, and deliberately not paginated: the grain is one match, whose
     *     darts are bounded by `best_of`. It is the *match list* that #26 pages, not
     *     one match's darts.
     */
    get: operations['get_match_darts_api_matches__match_id__darts_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/matches/{match_id}/state': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Match State
     * @description Everything the play screen needs, addressed by match rather than by leg.
     *
     *     The leg it reports is the match's latest, which is #17's `current_leg_id`
     *     and the same leg the match detail route names. For a match in progress that
     *     is the leg being played; for a finished one it is the leg that won it, shown
     *     complete; for an abandoned one it is wherever play stopped. `play.state`
     *     takes a *leg* id, so resolving the match first is not optional.
     */
    get: operations['get_match_state_api_matches__match_id__state_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Players */
    get: operations['list_players_api_players_get']
    put?: never
    /** Create Player */
    post: operations['create_player_api_players_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players/{player_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Player */
    patch: operations['update_player_api_players__player_id__patch']
    trace?: never
  }
  '/api/players/{player_id}/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Archive Player */
    post: operations['archive_player_api_players__player_id__archive_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stats/leaderboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Leaderboard
     * @description Everybody who has thrown at least `min_darts` x01 darts, best average first.
     *
     *     Archived players are left off, following #17's pickers: a leaderboard is a
     *     thing you are currently on. They keep every other statistic, and their own
     *     endpoint still answers.
     */
    get: operations['leaderboard_api_stats_leaderboard_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stats/matches/{match_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Match Stats
     * @description One match, per player and per leg.
     *
     *     `?match_id=` is accepted here for uniformity with the other two endpoints,
     *     but it may only name the match already in the path. Silently ignoring a
     *     contradiction, or answering about the other match, are both worse than
     *     saying so.
     */
    get: operations['match_stats_api_stats_matches__match_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stats/players/{player_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Player Stats
     * @description One player. A player who has never thrown gets zeroes and nulls, not a 404.
     */
    get: operations['player_stats_api_stats_players__player_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/version': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Deployed build */
    get: operations['version_api_version_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ApiError
     * @description What went wrong: a code to branch on, a sentence, and the specifics.
     */
    ApiError: {
      /** @description A closed vocabulary; branch on this, not on the message. */
      code: components['schemas']['ErrorCode']
      /**
       * Detail
       * @description Whatever the code implies. Pydantic's per-field errors for `validation_error`; `{'reason': ...}` for a refused domain rule, which is how several distinct 409s are told apart without matching on prose; the health report for `service_unavailable`; absent for the rest.
       * @default null
       */
      detail: unknown
      /**
       * Message
       * @description One sentence, safe to show a human.
       */
      message: string
    }
    /** BandsResponse */
    BandsResponse: {
      /** Hundred Plus */
      hundred_plus: number
      /** One Eighties */
      one_eighties: number
      /** One Forty Plus */
      one_forty_plus: number
      /** Sixty Plus */
      sixty_plus: number
    }
    /**
     * CheckoutResponse
     * @description Finishes for whoever throws next, or why there are none.
     *
     *     `paths` is empty exactly when `reason` is set, so a client never has to
     *     decide which of the two to believe.
     */
    CheckoutResponse: {
      /** Darts Left */
      darts_left: number
      /** Paths */
      paths: string[][]
      /** Player Id */
      player_id: number | null
      reason: components['schemas']['NoHintsReason'] | null
      /** Remaining */
      remaining: number | null
      /** Team Id */
      team_id: number | null
    }
    /** CricketResponse */
    CricketResponse: {
      /** Darts On Target */
      darts_on_target: number
      /** Darts Thrown */
      darts_thrown: number
      /** Marks */
      marks: number
      /** Marks Per Round */
      marks_per_round: number | null
      /** Targets */
      targets: components['schemas']['TargetResponse'][]
      /** Wasted Darts */
      wasted_darts: number
    }
    /** DartResponse */
    DartResponse: {
      /** Caused Bust */
      caused_bust: boolean
      /** Counted */
      counted: boolean
      /** Dart Id */
      dart_id: number
      /** Dart Index */
      dart_index: number
      /** Label */
      label: string
      /** Multiplier */
      multiplier: number
      /** Segment */
      segment: number
      /** Was Checkout Attempt */
      was_checkout_attempt: boolean
    }
    /**
     * DartWrite
     * @description One dart as a client reports it.
     *
     *     Validated here rather than by letting `Throw.__post_init__` raise inside the
     *     endpoint: a `ValueError` escaping a handler is a 500, whereas a refusal
     *     during request parsing is the field-level 422 the client can act on. By the
     *     time the endpoint runs, `Throw(segment, multiplier)` cannot fail.
     *
     *     `client_dart_id` is opaque text the client mints per dart, not a UUID --
     *     the column is a unique TEXT and nothing needs it to be more than that.
     *     It must be non-blank, since whitespace is not an identity.
     */
    DartWrite: {
      /** Client Dart Id */
      client_dart_id: string
      /** Multiplier */
      multiplier: number
      /** Segment */
      segment: number
    }
    /**
     * ErrorCode
     * @description Everything `error.code` is allowed to be.
     * @enum {string}
     */
    ErrorCode:
      | 'validation_error'
      | 'invalid_request'
      | 'not_found'
      | 'conflict'
      | 'service_unavailable'
      | 'internal'
    /**
     * ErrorEnvelope
     * @description The body of every failed `/api` response, whatever the status.
     */
    ErrorEnvelope: {
      error: components['schemas']['ApiError']
    }
    /**
     * FilterResponse
     * @description What the request was narrowed to, echoed back so a client can label a chart.
     */
    FilterResponse: {
      game_type: components['schemas']['GameType'] | null
      /** Match Id */
      match_id: number | null
      /** Since */
      since: string | null
      variant: components['schemas']['Variant'] | null
    }
    /**
     * GameConfig
     * @description Everything a match is configured with, validated once at creation.
     *
     *     Frozen and `extra="forbid"`: an unknown key is a typo or a stale client,
     *     and silently dropping it would mean the match is not the match that was
     *     asked for.
     */
    GameConfig: {
      /** Best Of */
      best_of: number
      /**
       * Fixed Team
       * @default 0
       */
      fixed_team: number
      game_type: components['schemas']['GameType']
      in_rule?: components['schemas']['Rule'] | null
      out_rule?: components['schemas']['Rule'] | null
      /** @default alternate */
      start_rule: components['schemas']['StartRule']
      /** Start Score */
      start_score?: number | null
      variant?: components['schemas']['Variant'] | null
    }
    /**
     * GameType
     * @description Which family of rules a match is played under.
     * @enum {string}
     */
    GameType: 'x01' | 'cricket'
    /**
     * HealthReport
     * @description The body of `/api/healthz`, and the `detail` of its 503.
     */
    HealthReport: {
      /** Auto Restored */
      auto_restored: boolean
      /** Checked At */
      checked_at: string | null
      /** Detail */
      detail: string | null
      /** Git Sha */
      git_sha: string
      /** Schema Version */
      schema_version: number | null
      status: components['schemas']['HealthState']
      /** Version */
      version: string
    }
    /**
     * HealthState
     * @description The three states of #12, plus the two only the server can be in.
     * @enum {string}
     */
    HealthState: 'healthy' | 'restored' | 'degraded' | 'unavailable' | 'not_started'
    /** LeaderboardBlock */
    LeaderboardBlock: {
      /** Min Darts */
      min_darts: number
      /**
       * Ranked By
       * @constant
       */
      ranked_by: 'three_dart_average'
      /** Rows */
      rows: components['schemas']['LeaderboardRowResponse'][]
    }
    /** LeaderboardResponse */
    LeaderboardResponse: {
      filter: components['schemas']['FilterResponse']
      /** Min Darts */
      min_darts: number
      /**
       * Ranked By
       * @constant
       */
      ranked_by: 'three_dart_average'
      /** Rows */
      rows: components['schemas']['LeaderboardRowResponse'][]
    }
    /** LeaderboardRowResponse */
    LeaderboardRowResponse: {
      /** Best Checkout */
      best_checkout: number | null
      /** Checkout Attempts */
      checkout_attempts: number
      /** Checkout Percentage */
      checkout_percentage: number | null
      /** Checkouts Hit */
      checkouts_hit: number
      /** Darts Thrown */
      darts_thrown: number
      /** Display Name */
      display_name: string
      /** Highest Visit */
      highest_visit: number | null
      /** One Eighties */
      one_eighties: number
      /** Player Id */
      player_id: number
      /** Three Dart Average */
      three_dart_average: number | null
    }
    /**
     * LegHistoryResponse
     * @description One leg's complete visit list, for the dart-by-dart breakdown.
     *
     *     `visits` is `VisitResponse`, the same model `/state` uses for the visit being
     *     thrown -- so a client has one dart type and one bust flag across both
     *     screens rather than a second vocabulary for the same row.
     */
    LegHistoryResponse: {
      /** Is Complete */
      is_complete: boolean
      /** Leg Id */
      leg_id: number
      /** Leg Index */
      leg_index: number
      /** Starting Team Id */
      starting_team_id: number
      /** Visits */
      visits: components['schemas']['VisitResponse'][]
      /** Winner Team Id */
      winner_team_id: number | null
    }
    /** LegLineResponse */
    LegLineResponse: {
      /** Darts Thrown */
      darts_thrown: number
      /** Leg Id */
      leg_id: number
      /** Leg Index */
      leg_index: number
      /** Marks Per Round */
      marks_per_round: number | null
      /** Player Id */
      player_id: number
      /** Three Dart Average */
      three_dart_average: number | null
      /** Won */
      won: boolean
    }
    /**
     * LegStateResponse
     * @description A leg, everything a board draws from it, and its hints.
     */
    LegStateResponse: {
      checkout: components['schemas']['CheckoutResponse']
      current_visit: components['schemas']['VisitResponse'] | null
      /** Darts Left */
      darts_left: number
      /** Darts Thrown */
      darts_thrown: number
      /** Is Complete */
      is_complete: boolean
      /** Leg Id */
      leg_id: number
      /** Leg Index */
      leg_index: number
      next_thrower: components['schemas']['ThrowerResponse'] | null
      previous_visit: components['schemas']['VisitResponse'] | null
      /** Starting Team Id */
      starting_team_id: number
      /** Teams */
      teams: components['schemas']['TeamLegResponse'][]
      /** Winner Team Id */
      winner_team_id: number | null
    }
    /**
     * MatchHistoryResponse
     * @description Every dart of a match, grouped the way it was thrown.
     */
    MatchHistoryResponse: {
      /** Legs */
      legs: components['schemas']['LegHistoryResponse'][]
      /** Match Id */
      match_id: number
    }
    /** MatchPage */
    MatchPage: {
      /** Items */
      items: components['schemas']['MatchResponse'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      /** Total */
      total: number
    }
    /** MatchReportResponse */
    MatchReportResponse: {
      filter: components['schemas']['FilterResponse']
      match: components['schemas']['MatchStatsResponse']
    }
    /** MatchResponse */
    MatchResponse: {
      /** Abandoned At */
      abandoned_at: string | null
      /** Completed At */
      completed_at: string | null
      config: components['schemas']['GameConfig']
      /** Created At */
      created_at: string
      /** Current Leg Id */
      current_leg_id: number | null
      /** Id */
      id: number
      status: components['schemas']['MatchStatus']
      /** Teams */
      teams: components['schemas']['TeamResponse'][]
      /** Winner Team Id */
      winner_team_id: number | null
    }
    /**
     * MatchStateResponse
     * @description The one fat read, and what every write returns.
     */
    MatchStateResponse: {
      active_leg: components['schemas']['LegStateResponse'] | null
      /** Active Leg Id */
      active_leg_id: number | null
      config: components['schemas']['GameConfig']
      current_leg: components['schemas']['LegStateResponse']
      /** Is Complete */
      is_complete: boolean
      /** Legs Won */
      legs_won: number[]
      /** Match Id */
      match_id: number
      status: components['schemas']['MatchStatus']
      /** Teams */
      teams: components['schemas']['TeamResponse'][]
      /** Winner Team Id */
      winner_team_id: number | null
    }
    /** MatchStatsResponse */
    MatchStatsResponse: {
      game_type: components['schemas']['GameType']
      /** Legs */
      legs: components['schemas']['LegLineResponse'][]
      /** Match Id */
      match_id: number
      /** Players */
      players: components['schemas']['PlayerStatsResponse'][]
      variant: components['schemas']['Variant'] | null
    }
    /**
     * MatchStatus
     * @enum {string}
     */
    MatchStatus: 'in_progress' | 'complete' | 'abandoned'
    /** MatchWrite */
    MatchWrite: {
      config: components['schemas']['GameConfig']
      /** Teams */
      teams: components['schemas']['TeamWrite'][]
    }
    /** MemberResponse */
    MemberResponse: {
      /** Display Name */
      display_name: string
      /** Is Archived */
      is_archived: boolean
      /** Member Index */
      member_index: number
      /** Player Id */
      player_id: number
    }
    /**
     * NoHintsReason
     * @description Why a leg has no checkout suggestions to offer.
     * @enum {string}
     */
    NoHintsReason:
      'not_x01' | 'leg_complete' | 'match_abandoned' | 'no_thrower' | 'not_open' | 'not_checkable'
    /** PlayerReportResponse */
    PlayerReportResponse: {
      filter: components['schemas']['FilterResponse']
      player: components['schemas']['PlayerStatsResponse']
    }
    /** PlayerResponse */
    PlayerResponse: {
      /** Accent Index */
      accent_index: number | null
      /** Created At */
      created_at: string
      /** Display Name */
      display_name: string
      /** Id */
      id: number
      /** Is Archived */
      is_archived: boolean
      /** Short Name */
      short_name: string | null
    }
    /** PlayerStatsResponse */
    PlayerStatsResponse: {
      cricket: components['schemas']['CricketResponse']
      /** Darts Thrown */
      darts_thrown: number
      /** Display Name */
      display_name: string
      /** Is Archived */
      is_archived: boolean
      /** Legs Played */
      legs_played: number
      /** Legs Won */
      legs_won: number
      /** Matches Played */
      matches_played: number
      /** Matches Won */
      matches_won: number
      /** Player Id */
      player_id: number
      /** Segments */
      segments: components['schemas']['SegmentResponse'][]
      x01: components['schemas']['X01Response']
    }
    /**
     * PlayerWrite
     * @description The editable half of a player, read slightly differently by each verb.
     *
     *     `display_name` is required either way. The other two are optional, and what
     *     leaving one out means depends on the verb:
     *
     *     * `POST` -- no accent means "choose one", and the server picks a colour no
     *       active player is using. No short name means there isn't one.
     *     * `PATCH` -- a field that is absent is left exactly as it was, and a field
     *       sent as `null` is cleared. Those are different requests, which is why the
     *       route reads `model_fields_set` rather than treating `None` as both.
     */
    PlayerWrite: {
      /** Accent Index */
      accent_index?: number | null
      /** Display Name */
      display_name: string
      /** Short Name */
      short_name?: string | null
    }
    /**
     * RebuildResponse
     * @description What the sweep found. `legs_changed` is 0 on a healthy database.
     */
    RebuildResponse: {
      /** Legs Changed */
      legs_changed: number
      /** Legs Visited */
      legs_visited: number
      /** Rows After */
      rows_after: number
      /** Rows Before */
      rows_before: number
    }
    /**
     * Rule
     * @description How a team is allowed to start scoring, and how they are allowed to finish.
     * @enum {string}
     */
    Rule: 'straight' | 'double' | 'master'
    /** SegmentResponse */
    SegmentResponse: {
      /** Darts */
      darts: number
      /** Multiplier */
      multiplier: number
      /** Segment */
      segment: number
    }
    /**
     * SnapshotResponse
     * @description The manifest, plus where it and its database went.
     *
     *     The same facts `snapshot.json` carries, so a client that called this and a
     *     client that read the file off #30's share are looking at one answer.
     */
    SnapshotResponse: {
      /** Created At */
      created_at: string
      /** Manifest Path */
      manifest_path: string
      /** Path */
      path: string
      /** Row Counts */
      row_counts: {
        [key: string]: number
      }
      /** Schema Version */
      schema_version: number
      /** Size Bytes */
      size_bytes: number
      /** Snapshot */
      snapshot: string
    }
    /**
     * StartRule
     * @enum {string}
     */
    StartRule: 'alternate' | 'loser_starts' | 'winner_starts' | 'fixed'
    /**
     * StatsExportResponse
     * @description The whole statistical picture, as one document that can be saved to disk.
     *
     *     Self-describing on purpose: something read off #30's share months later has
     *     to be able to say what it is, when it was true and what it was filtered to.
     */
    StatsExportResponse: {
      filter: components['schemas']['FilterResponse']
      /** Generated At */
      generated_at: string
      leaderboard: components['schemas']['LeaderboardBlock']
      /** Players */
      players: components['schemas']['PlayerStatsResponse'][]
      /** Schema Version */
      schema_version: number
    }
    /** TargetResponse */
    TargetResponse: {
      /** Hit Rate */
      hit_rate: number | null
      /** Hits */
      hits: number
      /** Marks */
      marks: number
      /** Target */
      target: number
    }
    /**
     * TeamLegResponse
     * @description One team's position. x01 fills `remaining`/`is_open`, cricket fills `marks`.
     */
    TeamLegResponse: {
      /** Darts Thrown */
      darts_thrown: number
      /** Is Open */
      is_open: boolean | null
      /** Marks */
      marks: {
        [key: string]: number
      } | null
      /** Points */
      points: number
      /** Remaining */
      remaining: number | null
      /** Team Id */
      team_id: number
      /** Three Dart Average */
      three_dart_average: number | null
    }
    /** TeamResponse */
    TeamResponse: {
      /** Id */
      id: number
      /** Is Solo */
      is_solo: boolean
      /** Members */
      members: components['schemas']['MemberResponse'][]
      /** Name */
      name: string | null
      /** Team Index */
      team_index: number
    }
    /** TeamWrite */
    TeamWrite: {
      /** Name */
      name?: string | null
      /** Player Ids */
      player_ids: number[]
    }
    /** ThrowerResponse */
    ThrowerResponse: {
      /** Display Name */
      display_name: string
      /** Player Id */
      player_id: number
      /** Team Id */
      team_id: number
    }
    /**
     * Variant
     * @description Which cricket is being played. Mark accounting is the same in all three.
     * @enum {string}
     */
    Variant: 'standard' | 'cutthroat' | 'quick'
    /**
     * VersionReport
     * @description What is deployed, for the footer of the app and for a deploy to verify.
     */
    VersionReport: {
      /** Git Sha */
      git_sha: string
      /** Version */
      version: string
    }
    /** VisitResponse */
    VisitResponse: {
      /** Darts */
      darts: components['schemas']['DartResponse'][]
      /** Is Bust */
      is_bust: boolean
      /** Is Complete */
      is_complete: boolean
      /** Player Id */
      player_id: number
      /** Score After */
      score_after: number
      /** Score Before */
      score_before: number
      /** Team Id */
      team_id: number
      /** Visit Id */
      visit_id: number
      /** Visit Index */
      visit_index: number
    }
    /** X01Response */
    X01Response: {
      /** Average Visit */
      average_visit: number | null
      bands: components['schemas']['BandsResponse']
      /** Best Checkout */
      best_checkout: number | null
      /** Checkout Attempts */
      checkout_attempts: number
      /** Checkout Percentage */
      checkout_percentage: number | null
      /** Checkouts Hit */
      checkouts_hit: number
      /** Darts Thrown */
      darts_thrown: number
      /** First Nine Average */
      first_nine_average: number | null
      /** First Nine Darts */
      first_nine_darts: number
      /** Highest Visit */
      highest_visit: number | null
      /** Points Scored */
      points_scored: number
      /** Three Dart Average */
      three_dart_average: number | null
      /** Visits */
      visits: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  rebuild_caches_api_admin_rebuild_caches_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RebuildResponse']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  take_snapshot_api_admin_snapshot_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SnapshotResponse']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  darts_csv_api_export_darts_csv_get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/csv': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  export_db_api_export_db_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/vnd.sqlite3': string
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  matches_csv_api_export_matches_csv_get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/csv': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  stats_json_api_export_stats_json_get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
        min_darts?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatsExportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  healthz_api_healthz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthReport']
        }
      }
      /** @description Degraded, unwritable, or not yet started */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  get_checkout_api_legs__leg_id__checkout_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        leg_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CheckoutResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  record_dart_api_legs__leg_id__darts_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        leg_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DartWrite']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchStateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  undo_dart_api_legs__leg_id__undo_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        leg_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchStateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  list_matches_api_matches_get: {
    parameters: {
      query?: {
        status?: components['schemas']['MatchStatus'] | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchPage']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  create_match_api_matches_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MatchWrite']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  get_match_api_matches__match_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        match_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  abandon_match_api_matches__match_id__abandon_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        match_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  get_match_darts_api_matches__match_id__darts_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        match_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchHistoryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  get_match_state_api_matches__match_id__state_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        match_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchStateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  list_players_api_players_get: {
    parameters: {
      query?: {
        include_archived?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  create_player_api_players_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerWrite']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  update_player_api_players__player_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerWrite']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  archive_player_api_players__player_id__archive_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  leaderboard_api_stats_leaderboard_get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
        min_darts?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeaderboardResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  match_stats_api_stats_matches__match_id__get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
      }
      header?: never
      path: {
        match_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MatchReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  player_stats_api_stats_players__player_id__get: {
    parameters: {
      query?: {
        game_type?: components['schemas']['GameType'] | null
        variant?: components['schemas']['Variant'] | null
        since?: string | null
        match_id?: number | null
      }
      header?: never
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  version_api_version_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VersionReport']
        }
      }
      /** @description Any other failure, in the standard error envelope. */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
}
