/**
 * Generate `src/api/schema.d.ts` from the OpenAPI schema the backend serves.
 *
 *   npm run gen:api          rewrite the committed types
 *   npm run gen:api:check    fail if they are stale or missing (what CI runs)
 *
 * The schema comes from `uv run darts-openapi`, which builds the real FastAPI
 * app against a throwaway database and fetches `/api/openapi.json` through the
 * route rather than reading the object -- so the types describe what a client
 * can actually reach. Needs both Python and Node on PATH, which is why CI runs
 * this in its own job rather than in the Node-only frontend one.
 *
 * `--check` regenerates in memory and compares. It deliberately does not write:
 * a check that repaired the thing it was checking would pass on a branch that
 * never committed the file, which is the one failure it exists to catch.
 *
 * Output is run through Prettier with the repo's own config, so the generated
 * file passes `npm run lint` like every other file rather than being exempted
 * from it.
 *
 * Note on the npm override: openapi-typescript still declares a peer of
 * typescript ^5.x while this repo is on 6.0. It only uses the compiler API to
 * build and print an AST, which 6.0 serves unchanged, so package.json overrides
 * the peer to the TypeScript already installed instead of resolving a second
 * copy. Revisit when upstream widens the range.
 */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import process from 'node:process'

import openapiTS, { astToString } from 'openapi-typescript'
import { format, resolveConfig } from 'prettier'

const FRONTEND = resolve(import.meta.dirname, '..')
const REPO_ROOT = resolve(FRONTEND, '..')
const TARGET = join(FRONTEND, 'src', 'api', 'schema.d.ts')

const BANNER = `/**
 * Generated by \`npm run gen:api\` from the backend's OpenAPI schema.
 * Do not edit by hand -- CI regenerates this and fails on any difference.
 */

`

/** The served OpenAPI document, via the backend's own dump tool. */
function fetchSchema() {
  const scratch = mkdtempSync(join(tmpdir(), 'darts-gen-api-'))
  try {
    const out = join(scratch, 'openapi.json')
    execFileSync('uv', ['run', 'darts-openapi', '-o', out], {
      cwd: REPO_ROOT,
      // The app logs to stdout; let it through to our stderr so a failure is
      // readable, and keep this script's own stdout clean.
      stdio: ['ignore', 'inherit', 'inherit'],
    })
    return JSON.parse(readFileSync(out, 'utf8'))
  } finally {
    rmSync(scratch, { recursive: true, force: true })
  }
}

async function render() {
  const ast = await openapiTS(fetchSchema())
  const source = BANNER + astToString(ast)
  const options = await resolveConfig(TARGET)
  return format(source, { ...options, filepath: TARGET })
}

async function main() {
  const check = process.argv.includes('--check')
  const generated = await render()

  if (!check) {
    mkdirSync(dirname(TARGET), { recursive: true })
    writeFileSync(TARGET, generated, 'utf8')
    console.log(`wrote ${TARGET} (${generated.split('\n').length} lines)`)
    return
  }

  let committed
  try {
    committed = readFileSync(TARGET, 'utf8')
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
    console.error(`${TARGET} does not exist.\nGenerate and commit it with:  npm run gen:api`)
    process.exitCode = 1
    return
  }

  if (committed !== generated) {
    console.error(
      `${TARGET} does not match the API the backend serves.\n` +
        `Regenerate and commit it with:  npm run gen:api`,
    )
    process.exitCode = 1
    return
  }

  console.log('src/api/schema.d.ts is up to date')
}

await main()
